name: Android Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with Buildozer
        # هذا هو الاسم الصحيح والمستقر للأداة
        uses: ArtemSerebrennkov/buildozer-action@v1
        with:
          buildozer_version: stable

      - name: Upload APK
        # استخدمنا النسخة v4 المتوافقة مع تحديثات جيت هوب الأخيرة
        uses: actions/upload-artifact@v4
        with:
          name: WhatsApp-Update-Final
          path: bin/*.apk
