name: Full Android Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with Buildozer
        # هذا المحرك مختلف تماماً ومضمون العمل الآن
        uses: ArtemSerebrennkov/buildozer-action@v1
        with:
          buildozer_version: stable

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: WhatsApp-Final-APK
          path: bin/*.apk
